name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]
jobs:
  run-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python main.py
      - uses: masterj3y/tupload@v1
        with:
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-user-id: ${{ secrtes.TELEGRAM_USER_ID }}
          file-path: main.py
